apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  name: golang-ingress-helm
  namespace: {{ .Values.namespace }}
spec:

  ingressClassName: nginx
  rules:
  - host: mohamedmahdimagroum-math.horizon-workspaces.com
    http:
      paths:
      - backend:
          service:
            name: golang-service-helm
            port:
              number: 80
        path: /
        pathType: ImplementationSpecific
  tls:
     - hosts:
         - mohamedmahdimagroum-math.horizon-workspaces.com
       secretName: math-go-tls
