apiVersion: v1
kind: Service
metadata:
  name: golang-service-helm
spec:
  selector:
    app: golang-helm
  ports:
    - protocol: TCP
      port: {{ .Values.service.port}}
      targetPort: {{ .Values.container.port}}
  type: {{ .Values.service.type}}
